### ISSUE TITLE
win修改下载路径

### ISSUE THREAD

**Issue by roronoa-chen** [DuC-cnZj/geekbang2md#2]
您好，我想请问Windows版的程序如何修改文件的下载路径呢？感谢您的分享

**Comment by duc-cnzj** [comment]
使用 -dir 参数

**Comment by roronoa-chen** [comment]
嗯嗯，
win版使用方式：
cmd打开exe目录，输入
geekbang2md-windows.exe -dir=d:\\xxx
即可更改下载目录，
感谢您的分享！！
