### ISSUE TITLE
下载地址为空

### ISSUE THREAD

**Issue by bambooslipsec** [DuC-cnZj/geekbang2md#5]
我用-hack命令，选择一个视频进行下载，但是提示下载地址为空。这是怎么回事？

**Comment by duc-cnzj** [comment]
@bambooslipsec 你网页端能看这门课的视频吗，要下载肯定是要有看这门课视频的权限

**Comment by bambooslipsec** [comment]
@duc-cnzj 多谢啊。问题解决了。
